#pragma once
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <ctype.h>
#include <limits.h>
#include <string.h>
#include <stdio.h>
#include <time.h>
#include <complex.h>
#include <math.h>
#include <tgmath.h>

#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <SDL2/SDL2_gfxPrimitives.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_net.h>
#include <SDL2/SDL_mixer.h>

#include "Types.h"
#include "Coords.h"
#include "Vec.h"
#include "GetInt.h"
#include "Colors.h"
#include "Timing.h"
#include "Graphics.h"
#include "Text.h"
#include "Image.h"
#include "Input.h"
#include "Events.h"
#include "File.h"
#include "Menu.h"
#include "DogeUtil.h"
#include "Poly.h"
#include "Examples.h"
